### ISSUE TITLE
[CHETNA-SNEHA] [Report] Information related to pregnant women and ANC services

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#51]
Aggregate report -- https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=51:51

Linelist -- https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=2:2

**Comment by garimadosar5** [comment]
QA Notes - 
- Instead of putting total as a column, can we put it as a row. It does not reflect by the column name that what total is it. **As discussed with Hetvi, they want that "total" as column.Will still confirm if its ok to have it as a row.**
- Following indicators are not getting calculated - **Fixed. There were issues with reporting views , that is fixed now.**
1. Pregnant women who received two doses of TT/TT booster	 
2. Pregnant women who consumed 100 IFA tablets
3. Pregnant women who have <18.5 BMI
- Indicator - "Pregnant women who have done delivery in the hospital". How is this getting calculated. **Check dynamic where parameter in linelist for conditions**
- Line list giving error for - "Pregnant women who completed minimum 4 visits". **Fixed**
- Indicator - "Pregnant women who have regisetered their name in the hospital", Number = 2 but in line list only one record is showing.
There was issue with reporting views.**Fixed**
